version: '3.6'
services:
  userDB:
    container_name: protaskify-user-service-postgres
    image: postgres:14.5
    command: postgres -c fsync=off -c synchronous_commit=off -c full_page_writes=off -c random_page_cost=1.0
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=newPassword
      - POSTGRES_DB=protaskify-user-db
    ports:
      - '5432:5432'
  taskDB:
    container_name: protaskify-task-service-postgres
    image: postgres:14.5
    command: postgres -c fsync=off -c synchronous_commit=off -c full_page_writes=off -c random_page_cost=1.0
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=newPassword
      - POSTGRES_DB=protaskify-task-db
    ports:
      - '6432:5432'

  adminer:
    container_name: protaskify-user-service-adminer
    image: adminer:4.8.1
    environment:
      ADMINER_DEFAULT_SERVER: postgresql
      ADMINER_DESIGN: hever
    ports:
      - "8080:8080"


  messageQueue:
    image: rabbitmq:3.12
    container_name: protaskify-rabbitmq
    ports:
      - 5672:5672
